import {receiptBytes,drawerBytes} from './escpos.js';
import {kitchenLines,prebillLines} from './ticket-model.js';import {fileURLToPath} from 'node:url';
import {createClient} from '@supabase/supabase-js';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {readFileSync} from 'node:fs';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
try{for(const line of readFileSync(new URL('./.env',import.meta.url),'utf8').split(/\r?\n/)){const entry=line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/);if(entry&&!process.env[entry[1]])process.env[entry[1]]=entry[2].trim()}}catch(e){if(e.code!=='ENOENT')throw e}
const exec=promisify(execFile);const {SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY,WINDOWS_PRINTER_NAME}=process.env;if(!SUPABASE_URL||!SUPABASE_SERVICE_ROLE_KEY||!WINDOWS_PRINTER_NAME)throw Error('Configura .env');if(process.platform!=='win32')throw Error('Este agente está diseñado para Windows 10');const sb=createClient(SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});async function print(job){
 const {data:o,error}=await sb.from('orders').select('*,order_items(*)').eq('id',job.order_id).single();if(error)throw error;
 if(o.deleted_at||o.status==='cancelled')throw Error('Pedido eliminado o cancelado: no imprimir');
 const dir=await mkdtemp(path.join(os.tmpdir(),'rame-')),file=path.join(dir,'ticket.bin');
 try{await writeFile(file,receiptBytes(job.job_type?.startsWith('prebill-')?prebillLines(o):kitchenLines(o,job)));await exec('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',fileURLToPath(new URL('./print-ticket.ps1',import.meta.url)),'-TicketFile',file,'-PrinterName',WINDOWS_PRINTER_NAME],{timeout:30000});}
 finally{await rm(dir,{recursive:true,force:true});}
}

async function openDrawer(){const dir=await mkdtemp(path.join(os.tmpdir(),'rame-drawer-')),file=path.join(dir,'drawer.bin');try{await writeFile(file,drawerBytes(Number(process.env.DRAWER_PIN)||0));await exec('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',fileURLToPath(new URL('./print-ticket.ps1',import.meta.url)),'-TicketFile',file,'-PrinterName',WINDOWS_PRINTER_NAME],{timeout:30000});}finally{await rm(dir,{recursive:true,force:true});}}
async function hardware(){const {data,error}=await sb.from('hardware_jobs').select('id,command,attempts').eq('status','pending').gt('expires_at',new Date().toISOString()).order('created_at').limit(10);if(error)throw error;for(const job of data||[]){const {data:claimed,error:e}=await sb.from('hardware_jobs').update({status:'claimed',claimed_at:new Date().toISOString(),attempts:job.attempts+1}).eq('id',job.id).eq('status','pending').gt('expires_at',new Date().toISOString()).select('id');if(e)throw e;if(!claimed?.length)continue;try{if(job.command!=='open_drawer')throw Error('Orden de hardware no permitida');await openDrawer();const r=await sb.from('hardware_jobs').update({status:'sent',sent_at:new Date().toISOString()}).eq('id',job.id);if(r.error)throw r.error;console.log('Orden manual de cajon enviada:',job.id);}catch(error){console.error('No se confirmo la orden del cajon:',error.message);await sb.from('hardware_jobs').update({status:'failed',error:error.message}).eq('id',job.id);}}}
let busy=false;async function tick(){if(busy)return;busy=true;try{let {data,error}=await sb.from('print_jobs').select('id,order_id,attempts,job_type').eq('status','pending').order('created_at',{ascending:true}).limit(10);if(error)throw error;for(let job of data||[]){let {data:claimed,error:e}=await sb.from('print_jobs').update({status:'claimed',claimed_at:new Date().toISOString(),attempts:job.attempts+1}).eq('id',job.id).eq('status','pending').select('id');if(e)throw e;if(!claimed?.length)continue;try{await print(job);const completed=await sb.from('print_jobs').update({status:'printed',printed_at:new Date().toISOString()}).eq('id',job.id);if(completed.error)throw completed.error;console.log('Enviado a cola Windows:',job.id)}catch(e){console.error('Impresión no confirmada',job.id,e.message);await sb.from('print_jobs').update({status:'failed',error:e.message}).eq('id',job.id)}}await hardware();}catch(e){console.error('Error de conexión',e.message)}finally{busy=false}}
console.log('Impresion ESC/POS sin apertura automatica del cajon.');console.log('Agente de impresión: '+WINDOWS_PRINTER_NAME+'. Los trabajos fallidos requieren revisión manual para evitar duplicados.');await tick();setInterval(tick,Math.max(3,Number(process.env.POLL_SECONDS)||5)*1000);
