import {configuredGroups,pricedUnit,canSellProduct} from './builder.js';
import {orderNumber,defaultSauces} from './order-workflow.js';
export function repeatCandidates(order,{products,categories,groups,options}){
 return (order.items||[]).map(i=>{try{const p=products.find(p=>p.id===i.product_id&&p.active&&canSellProduct(p,groups,options)&&categories.some(c=>c.id===p.category_id&&c.active));if(!p)throw Error('Producto no disponible en la carta actual');const gs=configuredGroups(p.id,groups,options),selected=Object.fromEntries(gs.map(g=>[g.id,[]]));for(const old of i.selected_options||[]){const matches=gs.flatMap(g=>g.choices.filter(o=>old.group_id&&old.option_id?g.id===old.group_id&&o.id===old.option_id:g.name===old.group&&o.name===old.name).map(o=>({g,o})));if(matches.length!==1)throw Error('Sus opciones cambiaron: agrégalo desde la carta');selected[matches[0].g.id].push(matches[0].o.id);}if(!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>30)throw Error('Revisa su cantidad desde la carta');const item={...pricedUnit(p,gs,selected,i.notes),quantity:i.quantity};return {original:i,item};}catch(e){return {original:i,error:e.message};}});
}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'$'+Number(n).toLocaleString('es-CL');
export async function openCustomerHistory({client,phone,catalog,onRepeat}){
 const {data,error}=await client.rpc('staff_customer_order_history',{p_phone:phone});if(error)throw error;
 const dialog=document.createElement('dialog');dialog.className='catalog-dialog';document.body.append(dialog);dialog.onclose=()=>dialog.remove();let selected=data?.[0],rows=[];
 function render(){rows=selected?repeatCandidates(selected,catalog):[];dialog.innerHTML=`<h2>Pedidos anteriores</h2>${data?.length?`<label>Pedido<select id="historyOrder">${data.map(o=>`<option value="${o.id}" ${o.id===selected.id?'selected':''}>#${orderNumber(o)} · ${new Date(o.created_at).toLocaleDateString('es-CL',{timeZone:'America/Santiago'})} · ${money(o.total)}</option>`).join('')}</select></label><p>${esc(selected.customer_name)} · ${esc(selected.delivery_address||'Retiro en local')}</p><p>Se crea otro borrador con precios actuales. Revisa domicilio, despacho y regalos antes de registrarlo.</p>${rows.map((r,i)=>`<article class="panel"><label class="checkline"><input type="checkbox" data-repeat="${i}" ${r.item?'checked':'disabled'}>${r.original.quantity} × ${esc(r.original.product_name)}</label>${r.error?`<p role="alert">${esc(r.error)}</p>`:`<p>${money(r.item.price)} por unidad${r.item.price!==r.original.unit_price?' · precio actualizado':''}</p><p>${esc(r.item.options.map(o=>o.name).join(', '))}</p><p>${esc(r.item.notes)}</p>`}</article>`).join('')}<p id="repeatTotal"></p>`:'<p>No hay pedidos anteriores para este teléfono.</p>'}<p id="historyNotice" role="status"></p><div class="actions"><button type="button" id="closeHistory" class="quiet">Cerrar</button>${data?.length?'<button type="button" id="repeatHistory">Crear borrador de este pedido</button>':''}</div>`;dialog.querySelector('#closeHistory').onclick=()=>dialog.close();if(!data?.length)return;dialog.querySelector('#historyOrder').onchange=e=>{selected=data.find(o=>o.id===e.target.value);render();};const picked=()=>Array.from(dialog.querySelectorAll('[data-repeat]:checked')).map(el=>rows[Number(el.dataset.repeat)].item);const total=()=>dialog.querySelector('#repeatTotal').textContent='Productos: '+money(picked().reduce((s,i)=>s+i.price*i.quantity,0))+' · despacho por recalcular';dialog.querySelectorAll('[data-repeat]').forEach(el=>el.onchange=total);total();dialog.querySelector('#repeatHistory').onclick=async e=>{const cart=picked();if(!cart.length){dialog.querySelector('#historyNotice').textContent='Selecciona al menos un producto disponible.';return;}e.target.disabled=true;try{await onRepeat({label:selected.customer_name||'Pedido habitual',fields:{name:selected.customer_name,phone:selected.customer_phone,address:selected.delivery_address||'',fulfillment:selected.fulfillment,channel:'counter',chopsticks:0},cart,sauces:defaultSauces(),delivery:null});dialog.close();}catch(error){dialog.querySelector('#historyNotice').textContent=error.message;e.target.disabled=false;}};}
 render();dialog.showModal();
}
