import {validPoint,pointFromText,DEFAULT_DELIVERY_CONFIG,validateDeliveryConfig} from './delivery-model.js';
import {mapsRoute} from './operations.js';
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clp=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n);
export async function invokeDelivery(client,body){const {data,error}=await client.functions.invoke('delivery-quote',{body});if(error){let message='No se pudo consultar el reparto. Revisa tu conexión.';try{message=(await error.context.json()).error||message;}catch{}throw Error(message);}if(data?.error)throw Error(data.error);return data;}
export function mountDelivery({target,addressInput,client,settings}){
 let point=null,quote=null,map=null,marker=null,busy=false,alive=true,revision=0;
 const start={lat:settings.delivery_origin_lat===null?NaN:Number(settings.delivery_origin_lat),lng:settings.delivery_origin_lng===null?NaN:Number(settings.delivery_origin_lng)};
 target.innerHTML=`<div class="delivery-controls"><button type="button" id="findDeliveryAddress">Ubicar domicilio</button><button type="button" id="showDeliveryMap">Elegir punto en mapa</button></div><p>Escribe calle, número y comuna. Si la búsqueda solo encuentra la calle, mueve el punto hasta el domicilio.</p><div id="deliveryCandidates"></div><details id="deliveryCoordinates"><summary>Pegar coordenadas del domicilio</summary><label>Latitud, longitud<input id="deliveryPointText" type="text" placeholder="-33.0600, -71.3900"></label><button type="button" id="useDeliveryPoint">Usar coordenadas</button></details><div id="deliveryMap" class="delivery-map" hidden></div><label class="account-checkbox"><input id="confirmDeliveryPoint" type="checkbox">Confirmo el domicilio del cliente en el punto señalado</label><button type="button" id="calculateDelivery">Calcular distancia y pago</button><p id="deliveryNotice" role="status">La app asignará el tramo automáticamente.</p><div id="deliveryQuote"></div><small>Mapa y datos © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>; búsqueda Photon, ruta OSRM. <a href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noopener">Corregir mapa</a>.</small>`;
 const $=selector=>target.querySelector(selector),notice=$('#deliveryNotice'),confirmed=$('#confirmDeliveryPoint');
 function invalidate(){revision++;quote=null;confirmed.checked=false;$('#deliveryQuote').innerHTML='';notice.textContent='Confirma el punto del domicilio y calcula nuevamente.';}
 addressInput.addEventListener('input',()=>{point=null;invalidate();$('#deliveryCandidates').innerHTML='';});
 confirmed.onchange=()=>{revision++;quote=null;$('#deliveryQuote').innerHTML='';};
 async function showMap(){if(!alive)return;$('#deliveryMap').hidden=false;if(!map){const {default:L}=await import('leaflet');await import('leaflet/dist/leaflet.css');if(!alive)return;
  const center=point||(validPoint(start)?start:{lat:-33.06,lng:-71.39});map=L.map($('#deliveryMap')).setView([center.lat,center.lng],15);
  L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
  if(validPoint(start))L.circleMarker([start.lat,start.lng],{radius:8,color:'#125cda',fillOpacity:1}).addTo(map).bindTooltip('Salida del local');
  map.on('click',event=>setPoint({lat:event.latlng.lat,lng:event.latlng.lng}));
 }
 map.invalidateSize();if(point)updateMarker();}
 async function updateMarker(){if(!map||!point)return;const {default:L}=await import('leaflet');if(!alive)return;if(marker)marker.remove();marker=L.circleMarker([point.lat,point.lng],{radius:10,color:'#de4930',fillOpacity:.85}).addTo(map).bindTooltip('Domicilio del cliente');map.setView([point.lat,point.lng],Math.max(map.getZoom(),16));}
 function setPoint(value){point=value;invalidate();notice.textContent='Punto seleccionado. Confirma que corresponde al domicilio.';updateMarker();}
 async function locate(){if(!addressInput.value.trim())throw Error('Escribe calle, número y comuna.');notice.textContent='Buscando domicilio…';const address=addressInput.value.trim();const data=await invokeDelivery(client,{action:'geocode',address});if(!alive||addressInput.value.trim()!==address)return;
  const candidates=data.candidates||[];$('#deliveryCandidates').innerHTML=candidates.map((c,i)=>`<button type="button" data-destination="${i}" class="secondary">${safe(c.label)}${c.precise?'':' · ubicación aproximada'}</button>`).join('');
  if(!candidates.length){await showMap();notice.textContent='No se encontró el domicilio. Selecciona el punto exacto en el mapa o pega sus coordenadas.';return;}
  target.querySelectorAll('[data-destination]').forEach(b=>b.onclick=()=>{setPoint(candidates[+b.dataset.destination]);showMap().catch(e=>notice.textContent=e.message);});
  if(candidates.length===1){setPoint(candidates[0]);await showMap();notice.textContent=candidates[0].precise?'Confirma el punto del domicilio antes de calcular.':'Se encontró una ubicación aproximada. Ajusta el punto en el mapa antes de confirmar.';}else notice.textContent='Elige el resultado correcto y confirma el domicilio en el mapa.';
 }
 async function run(action){if(busy)return;busy=true;const buttons=target.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{return await action();}catch(error){if(alive)notice.textContent=error.message;throw error;}finally{busy=false;buttons.forEach(b=>b.disabled=false);}}
 async function calculate(){return run(async()=>{if(!point){await locate();throw Error('Confirma el domicilio exacto en el mapa antes de registrar el delivery.');}if(!confirmed.checked)throw Error('Marca la confirmación del domicilio antes de calcular.');const address=addressInput.value.trim(),chosen={lat:point.lat,lng:point.lng},version=revision;notice.textContent='Calculando distancia por calles…';const result=await invokeDelivery(client,{action:'quote',address,point:chosen,confirmed:true});if(!alive||revision!==version||!confirmed.checked||!point||addressInput.value.trim()!==address||point.lat!==chosen.lat||point.lng!==chosen.lng){throw Error('El domicilio cambió. Calcula nuevamente.');}
  quote=result;notice.textContent='Tramo asignado automáticamente. Listo para registrar el pedido.';
  $('#deliveryQuote').innerHTML=`<div class="panel"><p><b>Distancia de ida:</b> ${(quote.distance_m/1000).toLocaleString('es-CL',{minimumFractionDigits:2,maximumFractionDigits:2})} km por calles</p><p><b>Tramo:</b> ${safe(quote.band_label)}</p><p><b>Pago al repartidor:</b> ${clp(quote.courier_pay)}</p><p><b>Delivery cobrado al cliente:</b> ${clp(quote.customer_fee)}</p><p>El pago al repartidor se registra cuando la entrega se completa. El cálculo vence en 20 minutos.</p><a href="${safe(mapsRoute(quote.point.lat+','+quote.point.lng,quote.origin.lat+','+quote.origin.lng))}" target="_blank" rel="noopener">Revisar ruta en Google Maps</a></div>`;return quote;
 });}
 $('#findDeliveryAddress').onclick=()=>run(locate).catch(()=>{});$('#showDeliveryMap').onclick=()=>showMap().catch(e=>notice.textContent=e.message);
 $('#useDeliveryPoint').onclick=()=>{const p=pointFromText($('#deliveryPointText').value);if(!p){notice.textContent='Pega coordenadas válidas: latitud, longitud.';return;}setPoint(p);showMap().catch(e=>notice.textContent=e.message);};
 $('#calculateDelivery').onclick=()=>calculate().catch(()=>{});
 return {getQuote:()=>quote&&Date.parse(quote.expires_at)>Date.now()?quote:null,calculate,destroy:()=>{alive=false;map?.remove();}};
}
export function mountDeliverySettings({target,settings,client,onSaved}){
 const c=settings.delivery_config||DEFAULT_DELIVERY_CONFIG;
 target.innerHTML=`<h2>Reparto y tarifas</h2><p>Se calcula la distancia de ida por calles desde el punto de salida hasta el domicilio confirmado. El pago al repartidor se guarda separado del cobro al cliente.</p><form id="deliverySettings"><p>Confirma el punto exacto del local antes de calcular repartos. Usa el GPS estando dentro del local o pega coordenadas verificadas.</p><button type="button" id="deliveryOriginGPS" class="quiet">Usar mi ubicación como salida</button><div class="account-grid"><label>Punto de salida: latitud<input name="lat" type="number" step="any" min="-90" max="90" value="${safe(settings.delivery_origin_lat??'')}" required></label><label>Punto de salida: longitud<input name="lng" type="number" step="any" min="-180" max="180" value="${safe(settings.delivery_origin_lng??'')}" required></label><label>Límite del primer tramo (km)<input name="near_km" type="number" step="0.1" min="0.1" value="${c.near_km}" required></label><label>Inicio del último tramo (km)<input name="far_km" type="number" step="0.1" min="0.2" max="100" value="${c.far_km}" required></label></div>${[['near','Primer tramo: menos del primer límite'],['mid','Tramo intermedio: desde el primer límite hasta menos del segundo'],['far','Último tramo: desde el segundo límite']].map(([key,label])=>`<fieldset><legend>${label}</legend><div class="account-grid"><label>Pago al repartidor ($)<input name="${key}_pay" type="number" min="0" max="1000000" step="1" value="${c[key+'_pay']}" required></label><label>Cobro de delivery al cliente ($)<input name="${key}_fee" type="number" min="0" max="1000000" step="1" value="${c[key+'_fee']}" required></label></div></fieldset>`).join('')}<p>Con los límites 3 y 5: exactamente 3 km corresponde al tramo intermedio y exactamente 5 km al último. Los cambios se aplican a pedidos nuevos; no modifican pagos ya guardados.</p><button type="submit">Guardar tarifas de reparto</button></form><p id="deliverySettingsNotice" role="status"></p>`;
 const form=target.querySelector('form'),notice=target.querySelector('#deliverySettingsNotice');
 target.querySelector('#deliveryOriginGPS').onclick=()=>{
  if(!navigator.geolocation){notice.textContent='Tu dispositivo no permite consultar GPS. Ingresa coordenadas verificadas.';return;}
  notice.textContent='Buscando tu ubicación. Debes estar dentro del local.';
  navigator.geolocation.getCurrentPosition(position=>{
   if(!target.isConnected)return;
   if(!Number.isFinite(position.coords.accuracy)||position.coords.accuracy>75){notice.textContent='El GPS tiene poca precisión. Acércate al exterior del local y vuelve a intentar.';return;}
   form.elements.lat.value=position.coords.latitude;form.elements.lng.value=position.coords.longitude;
   notice.textContent='Ubicación obtenida. Revisa los valores y pulsa Guardar tarifas de reparto.';
  },()=>{if(target.isConnected)notice.textContent='No se pudo obtener el GPS. Permite la ubicación precisa o ingresa coordenadas verificadas.';},{enableHighAccuracy:true,maximumAge:0,timeout:15000});
 };
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button[type=submit]');if(button.disabled)return;button.disabled=true;try{const f=new FormData(form),config=Object.fromEntries(Object.keys(DEFAULT_DELIVERY_CONFIG).map(k=>[k,Number(f.get(k))]));validateDeliveryConfig(config);const {error}=await client.rpc('owner_set_delivery_config',{p_config:config,p_lat:Number(f.get('lat')),p_lng:Number(f.get('lng')),p_expected:{config:settings.delivery_config,lat:settings.delivery_origin_lat,lng:settings.delivery_origin_lng}});if(error)throw error;notice.textContent='Tarifas guardadas. Se aplicarán a los próximos pedidos.';await onSaved();}catch(error){notice.textContent=error.message;}finally{button.disabled=false;}};
}
