import {communeFromAddress} from './delivery-areas.js';
import {validPoint,pointFromText,DEFAULT_DELIVERY_CONFIG,validateDeliveryConfig} from './delivery-model.js';
import {mapsRoute} from './operations.js';
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clp=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n);
export async function invokeDelivery(client,body){const {data,error}=await client.functions.invoke('delivery-quote',{body});if(error){let message='No se pudo consultar el reparto. Revisa tu conexión.';try{message=(await error.context.json()).error||message;}catch{}throw Error(message);}if(data?.error)throw Error(data.error);return data;}
export function mountDelivery({target,addressInput,client,settings,onChange=()=>{},initial=null}){
 let point=initial?.point||null,quote=initial?.quote||null,map=null,marker=null,busy=false,alive=true,revision=0;
 const start={lat:settings.delivery_origin_lat===null?NaN:Number(settings.delivery_origin_lat),lng:settings.delivery_origin_lng===null?NaN:Number(settings.delivery_origin_lng)};
 target.innerHTML=`<h3>Ubicación del delivery</h3><p>1. Ingresa la dirección. 2. Búscala en Google Maps. 3. Haz clic derecho en el punto del domicilio y copia sus coordenadas.</p><a id="searchGoogleMaps" class="map-search-link" href="https://www.google.com/maps" target="_blank" rel="noopener">Buscar esta dirección en Google Maps</a><div class="delivery-controls"><button type="button" id="showDeliveryMap">Ver / ajustar punto</button></div><label>Comuna del domicilio<select id="deliveryCommune"><option>Villa Alemana</option><option>Quilpué</option><option>Limache</option><option>Viña del Mar</option><option>Valparaíso</option><option>Concón</option><option value="">Otra comuna (escribir en dirección)</option></select></label><details><summary>Búsqueda alternativa en la app</summary><button type="button" id="findDeliveryAddress">Ubicar domicilio</button><div id="deliveryCandidates"></div></details><div id="deliveryCoordinates"><label>Pegar coordenadas o enlace completo de Google Maps<input id="deliveryPointText" type="text" autocomplete="off" placeholder="-33.0600, -71.3900"></label><p id="coordinatePreview" role="status"></p><button type="button" id="useDeliveryPoint">Usar coordenadas</button></div><div id="deliveryMap" class="delivery-map" hidden></div><label class="account-checkbox"><input id="confirmDeliveryPoint" type="checkbox">Confirmo el domicilio del cliente en el punto señalado</label><button type="button" id="calculateDelivery">Calcular distancia y pago</button><p id="deliveryNotice" role="status">Se aplica la zona o comuna configurada; fuera de ellas, la tarifa por distancia.</p><div id="deliveryQuote"></div><details><summary>Ingresar tarifa manual</summary><label class="account-checkbox"><input id="manualDelivery" type="checkbox">Usar tarifa manual para este pedido</label><p>Si el mapa no encuentra el domicilio, puedes registrar la dirección y la tarifa acordada. El repartidor verá si falta confirmar el punto.</p><label>Delivery cobrado al cliente ($)<input id="manualCustomerFee" type="number" min="0" max="1000000" step="1" value="0"></label><label>Pago al repartidor ($)<input id="manualCourierPay" type="number" min="0" max="1000000" step="1" value="0"></label><label>Motivo<input id="manualDeliveryReason" maxlength="250" placeholder="Ej.: domicilio no encontrado en el mapa"></label></details><small>Mapa y datos © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>; búsqueda Photon, ruta OSRM. <a href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noopener">Corregir mapa</a>.</small>`;
 const $=selector=>target.querySelector(selector),notice=$('#deliveryNotice'),confirmed=$('#confirmDeliveryPoint');
 function updateSearch(){const commune=$('#deliveryCommune').value,address=addressInput.value.trim(),query=address+(commune&&!address.toLocaleLowerCase('es').includes(commune.toLocaleLowerCase('es'))?', '+commune:'')+', Chile';$('#searchGoogleMaps').href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(query);}
 function inferCommune(){const select=$('#deliveryCommune'),found=communeFromAddress(addressInput.value,Array.from(select.options).map(o=>o.value).filter(Boolean));if(found)select.value=found;}
 function invalidate(){revision++;quote=null;confirmed.checked=false;$('#deliveryQuote').innerHTML='';notice.textContent='Confirma el punto del domicilio y calcula nuevamente.';onChange();}
 addressInput.addEventListener('input',()=>{inferCommune();updateSearch();$('#deliveryPointText').value='';$('#coordinatePreview').textContent='';point=null;invalidate();$('#deliveryCandidates').innerHTML='';});
 confirmed.onchange=()=>{revision++;quote=null;$('#deliveryQuote').innerHTML='';onChange();};
 $('#deliveryCommune').onchange=()=>{updateSearch();revision++;quote=null;$('#deliveryQuote').innerHTML='';notice.textContent='Comuna actualizada. Calcula nuevamente.';onChange();};
 for(const id of ['manualDelivery','manualCustomerFee','manualCourierPay','manualDeliveryReason'])$('#'+id).oninput=onChange;
 if(initial){confirmed.checked=!!initial.confirmed;$('#deliveryCommune').value=initial.commune||'Villa Alemana';$('#manualDelivery').checked=!!initial.manual;$('#manualCustomerFee').value=initial.fee||0;$('#manualCourierPay').value=initial.pay||0;$('#manualDeliveryReason').value=initial.reason||'';}
 if(!initial?.commune)inferCommune();updateSearch();if(point){$('#deliveryPointText').value=point.lat+', '+point.lng;$('#coordinatePreview').textContent='Punto guardado: '+point.lat+', '+point.lng;}
 async function showMap(){if(!alive)return;$('#deliveryMap').hidden=false;if(!map){const {default:L}=await import('leaflet');await import('leaflet/dist/leaflet.css');if(!alive)return;
  const center=point||(validPoint(start)?start:{lat:-33.06,lng:-71.39});map=L.map($('#deliveryMap')).setView([center.lat,center.lng],15);
  L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
  if(validPoint(start))L.circleMarker([start.lat,start.lng],{radius:8,color:'#125cda',fillOpacity:1}).addTo(map).bindTooltip('Salida del local');
  map.on('click',event=>setPoint({lat:event.latlng.lat,lng:event.latlng.lng}));
 }
 map.invalidateSize();if(point)updateMarker();}
 async function updateMarker(){if(!map||!point)return;const {default:L}=await import('leaflet');if(!alive)return;if(marker)marker.remove();marker=L.marker([point.lat,point.lng],{draggable:true,icon:L.divIcon({className:'delivery-pin',html:'📍',iconSize:[32,40],iconAnchor:[16,36]})}).addTo(map).bindTooltip('Arrastra hasta el domicilio');marker.on('dragend',()=>{const p=marker.getLatLng();setPoint({lat:p.lat,lng:p.lng});});map.setView([point.lat,point.lng],Math.max(map.getZoom(),16),{animate:false});}
 function setPoint(value){point=value;invalidate();notice.textContent='Punto seleccionado. Confirma que corresponde al domicilio.';updateMarker();}
 async function locate(){if(!addressInput.value.trim())throw Error('Escribe calle, número y comuna.');notice.textContent='Buscando domicilio…';const address=addressInput.value.trim();const commune=$('#deliveryCommune').value;const search=commune&&!address.toLocaleLowerCase('es').includes(commune.toLocaleLowerCase('es'))?address+', '+commune+', Chile':address;const data=await invokeDelivery(client,{action:'geocode',address:search});if(!alive||addressInput.value.trim()!==address)return;
  const candidates=data.candidates||[];$('#deliveryCandidates').innerHTML=candidates.map((c,i)=>`<button type="button" data-destination="${i}" class="secondary">${safe(c.label)}${c.precise?'':' · ubicación aproximada'}</button>`).join('');
  if(!candidates.length){await showMap();notice.textContent='No se encontró el domicilio. Selecciona el punto exacto en el mapa o pega sus coordenadas.';return;}
  target.querySelectorAll('[data-destination]').forEach(b=>b.onclick=()=>{setPoint(candidates[+b.dataset.destination]);showMap().catch(e=>notice.textContent=e.message);});
  if(candidates.length===1){setPoint(candidates[0]);await showMap();notice.textContent=candidates[0].precise?'Confirma el punto del domicilio antes de calcular.':'Se encontró una ubicación aproximada. Ajusta el punto en el mapa antes de confirmar.';}else notice.textContent='Elige el resultado correcto y confirma el domicilio en el mapa.';
 }
 async function run(action){if(busy)return;busy=true;const buttons=target.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{return await action();}catch(error){if(alive)notice.textContent=error.message;throw error;}finally{busy=false;buttons.forEach(b=>b.disabled=false);}}
 async function calculate(){return run(async()=>{if(!point)throw Error('Pega las coordenadas del domicilio y confirma el punto antes de calcular.');if(!confirmed.checked)throw Error('Marca la confirmación del domicilio antes de calcular.');const address=addressInput.value.trim(),chosen={lat:point.lat,lng:point.lng},version=revision;notice.textContent='Calculando distancia por calles…';const result=await invokeDelivery(client,{action:'quote',address,point:chosen,confirmed:true});if(!alive||revision!==version||!confirmed.checked||!point||addressInput.value.trim()!==address||point.lat!==chosen.lat||point.lng!==chosen.lng){throw Error('El domicilio cambió. Calcula nuevamente.');}
  const {data:pricing,error:priceError}=await client.rpc('staff_price_delivery_quote',{p_quote:result.id,p_commune:$('#deliveryCommune').value});if(priceError)throw priceError;if(!alive||revision!==version)throw Error('El domicilio cambió. Calcula nuevamente.');quote={...result,...pricing};onChange();notice.textContent='Tramo asignado automáticamente. Listo para registrar el pedido.';
  $('#deliveryQuote').innerHTML=`<div class="panel"><p><b>Distancia de ida:</b> ${(quote.distance_m/1000).toLocaleString('es-CL',{minimumFractionDigits:2,maximumFractionDigits:2})} km por calles</p><p><b>Tramo:</b> ${safe(quote.band_label)}</p><p><b>Pago al repartidor:</b> ${clp(quote.courier_pay)}</p><p><b>Delivery cobrado al cliente:</b> ${clp(quote.customer_fee)}</p><p>El pago al repartidor se registra cuando la entrega se completa. El cálculo vence en 20 minutos.</p><a href="${safe(mapsRoute(quote.point.lat+','+quote.point.lng,quote.origin.lat+','+quote.origin.lng))}" target="_blank" rel="noopener">Revisar ruta en Google Maps</a></div>`;return quote;
 });}
 $('#findDeliveryAddress').onclick=()=>run(locate).catch(()=>{});$('#showDeliveryMap').onclick=()=>showMap().catch(e=>notice.textContent=e.message);
 function readPoint(){const text=$('#deliveryPointText').value.trim(),p=pointFromText(text);if(!p){point=null;invalidate();$('#coordinatePreview').textContent=text?'No se reconoció un punto exacto. Copia latitud, longitud con clic derecho en Google Maps. Los enlaces cortos y la posición de la cámara del mapa no sirven.':'';return false;}setPoint(p);$('#coordinatePreview').textContent='Punto reconocido: '+p.lat+', '+p.lng;return true;}$('#deliveryPointText').addEventListener('input',readPoint);$('#useDeliveryPoint').onclick=()=>{if(readPoint())showMap().catch(e=>notice.textContent=e.message);};
 $('#calculateDelivery').onclick=()=>calculate().catch(()=>{});
 function getManual(){if(!$('#manualDelivery').checked)return null;const fee=Number($('#manualCustomerFee').value),pay=Number($('#manualCourierPay').value),reason=$('#manualDeliveryReason').value.trim();if(!addressInput.value.trim()||!Number.isSafeInteger(fee)||!Number.isSafeInteger(pay)||fee<0||pay<0||fee>1000000||pay>1000000||reason.length<3)throw Error('Revisa la dirección, los dos montos y el motivo de la tarifa manual.');if(point&&!confirmed.checked)throw Error('Confirma el punto seleccionado o cambia la dirección para registrar sin punto.');return {customer_fee:fee,courier_pay:pay,reason,lat:point?.lat??null,lng:point?.lng??null};}
 return {getManual,getState:()=>({point,quote,confirmed:confirmed.checked,commune:$('#deliveryCommune').value,manual:$('#manualDelivery').checked,fee:$('#manualCustomerFee').value,pay:$('#manualCourierPay').value,reason:$('#manualDeliveryReason').value}),setSavedPoint:p=>{setPoint(p);showMap().catch(e=>notice.textContent=e.message);},getQuote:()=>quote&&Date.parse(quote.expires_at)>Date.now()?quote:null,calculate,destroy:()=>{alive=false;if(map){map.stop();map.remove();map=null;marker=null;}}};
}
export {mountDeliverySettings} from './delivery-settings-ui.js';
