import {orderNumber,giftsText} from './order-workflow.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function mountDispatch({target,client,isCurrent}){
 let alive=true,timer=null,busy=false;
 target.innerHTML='<h2>Asignación de repartidores</h2><button id="refreshDispatch" class="quiet">Actualizar asignación</button><p id="dispatchNotice" role="status"></p><div id="dispatchContent"></div>';
 const notice=target.querySelector('#dispatchNotice'),content=target.querySelector('#dispatchContent');
 async function refresh(){clearTimeout(timer);try{const {data,error}=await client.rpc('staff_dispatch_board');if(error)throw error;if(!alive||!isCurrent())return;const drivers=data.drivers||[],orders=data.orders||[],choices=Object.fromEntries(Array.from(content.querySelectorAll('[data-dispatch-select]')).map(s=>[s.dataset.dispatchSelect,s.value]));content.innerHTML=`<div class="actions">${drivers.map(d=>`<span class="panel">${esc(d.name)} · ${d.on_shift?'Jornada abierta':'Sin jornada abierta'} · ${d.load} pedidos activos</span>`).join('')||'<p>Administración debe habilitar un usuario con función Repartidor.</p>'}</div><h3>Listos para despacho</h3>${orders.filter(o=>o.status==='ready').map(o=>`<article class="panel"><b>Comanda #${orderNumber(o)} · ${esc(o.customer_name)}</b><p>${esc(o.delivery_address)}</p><p>${esc(giftsText(o))}</p>${o.scheduled_at?`<p>Agendado: ${new Date(o.scheduled_at).toLocaleString('es-CL',{timeZone:'America/Santiago'})}</p>`:''}<label>Repartidor<select data-dispatch-select="${o.id}"><option value="">Seleccionar repartidor</option>${drivers.map(d=>`<option value="${d.id}">${esc(d.name)} · ${d.load} pedidos${d.on_shift?'':' · sin jornada abierta'}</option>`).join('')}</select></label><div class="actions"><button data-assign-dispatch="${o.id}" ${drivers.length?'':'disabled'}>Asignar pedido</button></div></article>`).join('')||'<p>No hay pedidos listos pendientes de asignación.</p>'}<h3>Asignados y en camino</h3>${orders.filter(o=>o.status!=='ready').map(o=>`<article class="panel"><b>#${orderNumber(o)} · ${esc(o.customer_name)}</b><p>${esc(drivers.find(d=>d.id===o.courier_id)?.name||'Repartidor')} · ${o.status==='assigned'?'Empacando / asignado':'En camino'}</p><p>${esc(o.delivery_address)}</p></article>`).join('')||'<p>Sin repartos activos.</p>'}`;content.querySelectorAll('[data-dispatch-select]').forEach(s=>{s.value=choices[s.dataset.dispatchSelect]||'';});content.querySelectorAll('[data-assign-dispatch]').forEach(b=>b.onclick=async()=>{if(busy)return;const driver=content.querySelector(`[data-dispatch-select="${b.dataset.assignDispatch}"]`).value;if(!driver){notice.textContent='Selecciona un repartidor.';return;}busy=true;b.disabled=true;try{const {error}=await client.rpc('staff_assign_courier',{p_order_id:b.dataset.assignDispatch,p_courier:driver});if(error)throw error;notice.textContent='Pedido asignado. Ya aparece en la app del repartidor.';await refresh();}catch(e){notice.textContent=e.message;b.disabled=false;}finally{busy=false;}});}catch(e){if(alive)notice.textContent=e.message;}finally{if(alive&&isCurrent())timer=setTimeout(()=>{if(busy)timer=setTimeout(refresh,2000);else refresh();},20000);}}
 target.querySelector('#refreshDispatch').onclick=refresh;await refresh();return()=>{alive=false;clearTimeout(timer);};
}
