select set_config('request.jwt.claim.sub',(select id::text from public.profiles where role='owner' and active limit 1),true);
do $$ begin if not exists(select 1 from public.cash_sessions where closed_at is null) then perform public.cash_open(0);end if;end $$;
set local role authenticated;
do $$
declare oid uuid;oid2 uuid;rid uuid:=gen_random_uuid();pid uuid;payload jsonb;v integer;nextnum integer;first_session uuid;second_session uuid;oldtotal integer;ts timestamptz;
begin
 select p.id into pid from public.products p where p.active and p.base_price>0 and exists(select 1 from public.categories c where c.id=p.category_id and c.active) and not exists(select 1 from public.option_groups g where g.product_id=p.id and g.active and g.min_select>0) limit 1;
 if pid is null then raise exception 'Missing simple priced product';end if;
 payload:=jsonb_build_object('name','PRUEBA NUEVO FLUJO','phone','+56900000001','fulfillment','pickup','channel','counter','items',jsonb_build_array(jsonb_build_object('product_id',pid,'quantity',1,'options','[]'::jsonb,'notes','Pollo por palta')),'gift_sauces','[{"name":"Soya","quantity":2}]'::jsonb,'chopsticks',3,'delivery_notes','Llamar al llegar','scheduled_at',null);
 select id into first_session from public.cash_sessions where closed_at is null;
 select coalesce(max(daily_number),0)+1 into nextnum from public.orders where comanda_session_id=first_session;
 oid:=public.staff_submit_order(payload,rid);
 if not exists(select 1 from public.orders where id=oid and status='confirmed' and payment_method is null and comanda_session_id=first_session and daily_number=nextnum and chopsticks=3 and customer_id is not null) then raise exception 'Submit/number/customer failed';end if;
 if (select count(*) from public.print_jobs where order_id=oid)<>1 then raise exception 'Print not immediate';end if;
 if public.staff_submit_order(payload,rid)<>oid or (select count(*) from public.print_jobs where order_id=oid)<>1 then raise exception 'Idempotent retry failed';end if;
 if exists(select 1 from public.cash_movements where order_id=oid) then raise exception 'Premature payment';end if;
 begin perform public.record_order_payment(oid,first_session);raise exception 'Unknown method charged';exception when others then if sqlerrm not like '%Confirma el medio%' then raise;end if;end;
 if public.staff_find_customer('900000001')->>'name'<>'PRUEBA NUEVO FLUJO' then raise exception 'Customer lookup failed';end if;
 update public.print_jobs set status='printed' where order_id=oid;
 select updated_at into ts from public.orders where id=oid;
 payload:=payload||jsonb_build_object('name','PRUEBA EDITADO','items',(select jsonb_agg(jsonb_build_object('id',id,'notes','Palta por pollo')) from public.order_items where order_id=oid));
 perform public.staff_update_order_details(oid,ts,payload);
 if (select count(*) from public.print_jobs where order_id=oid)<>2 then raise exception 'Correction missing';end if;
 if (select name from public.customers where id=(select customer_id from public.orders where id=oid))<>'PRUEBA EDITADO' then raise exception 'Customer edit not saved';end if;
 perform public.staff_record_order_payment(oid,first_session,'card');
 if not exists(select 1 from public.cash_movements where order_id=oid and method='card') then raise exception 'Cash method wrong';end if;
 begin perform public.staff_record_order_payment(oid,first_session,'cash');raise exception 'Double charge accepted';exception when others then if sqlerrm not like '%no cobrable%' then raise;end if;end;
 v:=public.staff_save_order_draft(rid,'{"cart":[]}'::jsonb,0);if v<>1 then raise exception 'Draft insert failed';end if;
 v:=public.staff_save_order_draft(rid,'{"cart":[1]}'::jsonb,1);if v<>2 then raise exception 'Draft update failed';end if;
 begin perform public.staff_save_order_draft(rid,'{}',1);raise exception 'Stale overwrite';exception when others then if sqlerrm not like '%otra sesión%' then raise;end if;end;
 payload:=payload||jsonb_build_object('fulfillment','delivery','address','DOMICILIO DE PRUEBA 123','items',jsonb_build_array(jsonb_build_object('product_id',pid,'quantity',1,'options','[]'::jsonb,'notes','')),'manual_delivery',jsonb_build_object('customer_fee',2500,'courier_pay',1800,'reason','No encontrado','lat',null,'lng',null));
 oid2:=public.staff_submit_order(payload,gen_random_uuid());
 if not exists(select 1 from public.orders where id=oid2 and manual_delivery and delivery_fee=2500 and courier_delivery_pay=1800 and delivery_latitude is null and delivery_distance_m is null and daily_number=nextnum+1) then raise exception 'Manual delivery failed';end if;
 select updated_at into ts from public.orders where id=oid2;
 payload:=payload||jsonb_build_object('items',(select jsonb_agg(jsonb_build_object('id',id,'notes','')) from public.order_items where order_id=oid2),'delivery_change',jsonb_build_object('address','DOMICILIO CORREGIDO 456','manual_delivery',jsonb_build_object('customer_fee',3000,'courier_pay',2000,'reason','Nueva dirección','lat',-33.06,'lng',-71.39)));
 perform public.staff_update_order_details(oid2,ts,payload);
 if not exists(select 1 from public.orders where id=oid2 and delivery_fee=3000 and delivery_address='DOMICILIO CORREGIDO 456' and courier_delivery_pay=2000 and delivery_latitude=-33.06) then raise exception 'Delivery edit failed';end if;
 payload:=payload||jsonb_build_object('items',jsonb_build_array(jsonb_build_object('product_id',pid,'quantity',1,'options','[]'::jsonb,'notes','')),'delivery_change',null);
 perform public.cash_close(first_session,0);
 begin perform public.staff_submit_order(payload,gen_random_uuid());raise exception 'Closed cash accepted';exception when others then if sqlerrm not like '%Abre la caja%' then raise;end if;end;
 second_session:=public.cash_open(0);
 oid2:=public.staff_submit_order(payload,gen_random_uuid());
 if not exists(select 1 from public.orders where id=oid2 and comanda_session_id=second_session and daily_number=1) then raise exception 'Opening did not reset counter';end if;
end $$;
reset role;
select 'PASS: session counter, reset, immediate print, idempotency, client reuse, gifts, edits, manual delivery, cash, draft conflict' result;
select set_config('request.jwt.claim.sub',(select id::text from public.profiles where role='owner' and active limit 1),true);
do $$ declare worker uuid;entry uuid;begin
 select id into worker from public.profiles where role in ('worker','courier') and active limit 1;
 if worker is null then raise exception 'Employee fixture missing';end if;
 insert into public.time_entries(worker_id,clock_in,clock_out,hourly_rate,unpaid_break_minutes,notes) values(worker,now()-interval '3 hours',now()-interval '1 hour',4000,15,'PRUEBA REMUNERACIONES') returning id into entry;
 perform set_config('rame.test_worker',worker::text,true);perform set_config('rame.test_entry',entry::text,true);
end $$;
set local role authenticated;
do $$ declare worker uuid:=current_setting('rame.test_worker')::uuid;report jsonb;payment uuid;rid uuid:=gen_random_uuid();begin
 payment:=public.owner_record_payroll_payment(worker,1000,'transfer','PRUEBA REMUNERACIONES',rid);
 if public.owner_record_payroll_payment(worker,1000,'transfer','PRUEBA REMUNERACIONES',rid)<>payment then raise exception 'Duplicate wage payment';end if;
 report:=public.staff_payroll_report((now() at time zone 'America/Santiago')::date-1,(now() at time zone 'America/Santiago')::date);
 if not exists(select 1 from jsonb_array_elements(report->'workers') w,jsonb_array_elements(w->'shifts') s where s->>'id'=current_setting('rame.test_entry') and (s->>'base')::integer=7000 and (s->>'minutes')::numeric=105) then raise exception 'Wage math failed';end if;
 perform set_config('request.jwt.claim.sub',worker::text,true);
 report:=public.staff_payroll_report((now() at time zone 'America/Santiago')::date-1,(now() at time zone 'America/Santiago')::date);
 if jsonb_array_length(report->'workers')<>1 or report->'workers'->0->>'id'<>worker::text then raise exception 'Employee saw another wage';end if;
 if exists(select 1 from public.order_drafts) then raise exception 'Employee saw staff drafts';end if;
 begin perform public.staff_find_customer('900000001');raise exception 'Employee saw customers';exception when others then if sqlerrm not like '%No autorizado%' then raise;end if;end;
 begin perform public.owner_record_payroll_payment(worker,1000,'cash','Invalid',gen_random_uuid());raise exception 'Employee recorded wage payment';exception when others then if sqlerrm not like '%Solo administración%' then raise;end if;end;
 if has_function_privilege('anon','public.staff_submit_order(jsonb,uuid)','execute') or has_function_privilege('anon','public.staff_payroll_report(date,date)','execute') then raise exception 'Anonymous access';end if;
end $$;
reset role;
select 'PASS: wage math, server role checks, own-worker privacy, paid records, idempotency, employee/anon denial' result;
select set_config('request.jwt.claim.sub',(select id::text from public.profiles where role='owner' and active limit 1),true);
set local role authenticated;
do $$ declare rid uuid:=gen_random_uuid();jid uuid;oid uuid;printid uuid;begin
 jid:=public.staff_open_drawer(rid);
 if public.staff_open_drawer(rid)<>jid then raise exception 'Duplicate drawer job';end if;
 if not exists(select 1 from public.hardware_jobs where id=jid and command='open_drawer' and expires_at<=now()+interval '31 seconds') then raise exception 'Drawer expiry missing';end if;
 select id into oid from public.orders where request_id is not null and status='confirmed' limit 1;
 printid:=public.staff_queue_order_print(oid,'prebill',rid);
 if public.staff_queue_order_print(oid,'prebill',rid)<>printid then raise exception 'Duplicate prebill';end if;
 perform set_config('request.jwt.claim.sub',current_setting('rame.test_worker'),true);
 if exists(select 1 from public.hardware_jobs) then raise exception 'Employee saw hardware';end if;
 begin perform public.staff_open_drawer(gen_random_uuid());raise exception 'Employee opened drawer';exception when others then if sqlerrm not like '%No autorizado%' then raise;end if;end;
 begin perform public.staff_queue_order_print(oid,'kitchen',gen_random_uuid());raise exception 'Employee printed orders';exception when others then if sqlerrm not like '%No autorizado%' then raise;end if;end;
end $$;
reset role;
select 'PASS: manual drawer, short expiry, idempotent print and worker denial' result;
