import {PAYMENT_NAMES} from './operations.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n);
const date=x=>new Date(x).toLocaleString('es-CL',{timeZone:'America/Santiago'});
const duration=n=>`${Math.floor(Number(n)/60)} h ${Math.floor(Number(n)%60)} min`;
export async function renderPayroll({client,target,profile,isCurrent}){
 let today=new Date().toLocaleDateString('en-CA',{timeZone:'America/Santiago'}),from=today.slice(0,8)+'01',to=today;
 let worker=profile.role==='owner'?'':profile.id;
 async function load(){
 const {data,error}=await client.rpc('staff_payroll_report',{p_from:from,p_to:to});if(!isCurrent())return;if(error){target.innerHTML='<p role="alert">'+esc(error.message)+'</p>';return;}
 const workers=data.workers||[],chosen=workers.filter(w=>!worker||w.id===worker);
 target.innerHTML=`<h1>${profile.role==='owner'?'Remuneraciones del personal':'Mis horas y remuneraciones'}</h1><form id="payrollFilters" class="panel"><div class="account-grid"><label>Desde<input name="from" type="date" value="${from}" required></label><label>Hasta<input name="to" type="date" value="${to}" required></label>${profile.role==='owner'?`<label>Trabajador<select name="worker"><option value="">Todos</option>${workers.map(w=>`<option value="${w.id}" ${worker===w.id?'selected':''}>${esc(w.name)}</option>`).join('')}</select></label>`:''}</div><button>Ver desglose</button></form><p>Las jornadas cerradas se incluyen en el período de su salida. Las jornadas en curso muestran una estimación provisional. Se usa la tarifa registrada en cada jornada y se descuentan las pausas no remuneradas.</p>${chosen.map(w=>{
 const closed=w.shifts.filter(s=>s.clock_out),base=closed.reduce((n,s)=>n+Number(s.base),0),delivery=w.deliveries.reduce((n,d)=>n+Number(d.pay||0),0),paid=w.payments.reduce((n,p)=>n+Number(p.amount),0),balance=Number(w.earned)+Number(w.delivery_earned)-Number(w.paid);
 return `<section class="panel"><h2>${esc(w.name)}</h2><div class="summary-grid"><div><b>Horas cerradas del período</b><h3>${duration(closed.reduce((n,s)=>n+Number(s.minutes),0))}</h3></div><div><b>Base del período</b><h3>${money(base)}</h3></div><div><b>Entregas del período</b><h3>${money(delivery)}</h3></div><div><b>Devengado del período</b><h3>${money(base+delivery)}</h3></div><div><b>Pagos registrados en el período</b><h3>${money(paid)}</h3></div></div><h3>Acumulado histórico</h3><p>Horas y entregas devengadas: <b>${money(Number(w.earned)+Number(w.delivery_earned))}</b><br>Pagos registrados: <b>${money(w.paid)}</b><br>${balance>=0?'Saldo pendiente':'Anticipo a favor del trabajador'}: <b>${money(Math.abs(balance))}</b></p><details open><summary>Jornadas y tarifa aplicada</summary>${w.shifts.map(s=>`<article class="payroll-line"><b>${esc(date(s.clock_in))}</b> → ${s.clock_out?esc(date(s.clock_out)):'En curso'}<p>${duration(s.minutes)} · Pausa: ${s.unpaid_break_minutes} min · ${money(s.hourly_rate)}/hora · <b>${money(s.base)}${s.clock_out?'':' (provisional)'}</b></p></article>`).join('')||'<p>Sin jornadas en este período.</p>'}</details><details><summary>Pagos por entregas</summary>${w.deliveries.map(d=>`<p>Pedido #${d.number} · ${esc(date(d.at))} · ${money(d.pay)}</p>`).join('')||'<p>Sin entregas completadas.</p>'}</details><details><summary>Pagos de remuneraciones registrados</summary>${w.payments.map(p=>`<p>${esc(date(p.paid_at))} · ${money(p.amount)} · ${esc(PAYMENT_NAMES[p.method])}<br>${esc(p.notes)}</p>`).join('')||'<p>Sin pagos registrados.</p>'}</details>${profile.role==='owner'?`<button data-pay-worker="${w.id}">Registrar pago ya realizado</button>`:''}</section>`;
 }).join('')||'<p>Sin registros.</p>'}<p class="muted">Los montos son un control de remuneración por horas y repartos. Los pagos aquí registrados deben corresponder a pagos realizados por administración. No se ejecutan transferencias ni se generan egresos de caja desde esta pantalla.</p>`;
 target.querySelector('#payrollFilters').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);from=f.get('from');to=f.get('to');worker=f.get('worker')||profile.id;if(profile.role==='owner')worker=f.get('worker')||'';load();};
 target.querySelectorAll('[data-pay-worker]').forEach(b=>b.onclick=()=>payment(workers.find(w=>w.id===b.dataset.payWorker)));
 }
 function payment(w){const dialog=document.createElement('dialog'),request=crypto.randomUUID();dialog.className='catalog-dialog';dialog.innerHTML=`<h2>Registrar pago a ${esc(w.name)}</h2><form><label>Monto pagado<input name="amount" type="number" min="1" max="1000000000" step="1" required></label><label>Medio de pago<select name="method">${Object.entries(PAYMENT_NAMES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>Referencia o concepto<textarea name="notes" maxlength="500" placeholder="Ej.: anticipo octubre, transferencia realizada"></textarea></label><p data-error role="alert"></p><div class="actions"><button type="button" data-close>Cancelar</button><button>Guardar pago realizado</button></div></form>`;document.body.append(dialog);dialog.onclose=()=>dialog.remove();dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;const f=new FormData(e.target);const {error}=await client.rpc('owner_record_payroll_payment',{p_worker:w.id,p_amount:Number(f.get('amount')),p_method:f.get('method'),p_notes:f.get('notes'),p_request:request});if(error){dialog.querySelector('[data-error]').textContent=error.message;e.submitter.disabled=false;return;}dialog.close();load();};dialog.showModal();}
 await load();
}
