import {configuredGroups,validateSelection,pricedUnit,changeCount} from './builder.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clp=n=>'$'+Number(n||0).toLocaleString('es-CL');
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const isPromo=p=>/tabla|promoci[oó]n|promo/i.test(p.name||'');
const isHandroll=p=>/hand\s*roll/i.test(p.name||'')&&!isPromo(p);
const isChange=g=>/cambio/i.test(g.name||'');
const isWrap=g=>/envoltura|cobertura/i.test(g.name||'');
const unitOf=g=>{const m=String(g.name).match(/(?:hand\s*roll|roll)\s*(?:xl\s*)?(\d+)/i);return m?Number(m[1]):0;};
function allowOption(p,g,o){if(!isHandroll(p)||!isWrap(g))return true;const name=norm(o.name);return /nori|panko/.test(name);}
export function openProductBuilder({product:p,groups,options,previous=null,onSave}){
 const gs=configuredGroups(p.id,groups,options).map(g=>({...g,choices:g.choices.filter(o=>allowOption(p,g,o))}));
 const selected=Object.fromEntries(gs.map(g=>[g.id,(previous?.options||[]).filter(o=>o.group_id===g.id&&g.choices.some(x=>x.id===o.option_id)).map(o=>o.option_id)]));
 const promo=isPromo(p),handroll=isHandroll(p),units=[...new Set(gs.map(unitOf).filter(Boolean))].sort((a,b)=>a-b),tabbed=promo&&units.length>=2;
 const ordered=tabbed?[...gs].sort((a,b)=>(unitOf(a)||999)-(unitOf(b)||999)||a.sort_order-b.sort_order):gs;
 const dialog=document.createElement('dialog');dialog.className='product-builder quick-builder';document.body.append(dialog);dialog.onclose=()=>dialog.remove();
 const groupsHtml=ordered.map(g=>`<fieldset class="quick-group" data-group="${esc(g.id)}" ${tabbed&&unitOf(g)?`data-roll="${unitOf(g)}"`:''}><legend>${esc(g.name)} <small>${g.min_select?`Elegir ${g.min_select}${g.min_select!==g.max_select?'–'+g.max_select:''}`:'Opcional'}</small></legend>${g.min_select===0?`<button type="button" class="quiet quick-clear" data-clear="${esc(g.id)}">Sin adicional</button>`:''}<div class="choices">${g.choices.map(o=>`<button type="button" class="choice" data-group-option="${esc(g.id)}" data-option="${esc(o.id)}" aria-pressed="false"><span>${esc(o.name)}</span><b>${o.price_delta?'+'+clp(o.price_delta):'Incluido'}</b></button>`).join('')}</div><small class="quick-count" data-count="${esc(g.id)}"></small></fieldset>`).join('');
 dialog.innerHTML=`<div class="wizard-head"><h2>${esc(p.name)}</h2><button type="button" class="quiet" data-close>✕</button></div>${promo?'<p class="muted">Hasta 3 cambios en total, combinando envoltura y relleno.</p><p id="changeCounter" aria-live="polite"></p>':''}${tabbed?`<nav class="roll-tabs">${units.map(n=>`<button type="button" class="quiet roll-tab" data-roll-tab="${n}">Handroll ${n}</button>`).join('')}</nav><div class="roll-current"></div>`:''}${handroll?'<p class="muted">Frío: nori · Caliente: panko. Selecciona también si lleva queso crema.</p><fieldset class="quick-group"><legend>Queso crema</legend><div class="choices"><button type="button" class="choice" data-cream="si">Con queso crema</button><button type="button" class="choice" data-cream="no">Sin queso crema</button></div></fieldset>':''}<div class="quick-groups ${tabbed?'promo-quick-groups':''}">${groupsHtml}</div><label>Observaciones para cocina<textarea id="unitNotes" maxlength="500">${esc(previous?.notes||'')}</textarea></label><p class="quick-error" role="alert" aria-live="polite"></p><div class="wizard-actions"><strong id="unitPrice"></strong>${tabbed?'<button type="button" class="quiet" data-prev-roll>Anterior</button><button type="button" data-next-roll>Siguiente handroll →</button>':''}<button type="button" data-save>${previous?'Guardar cambios':'Agregar al pedido'}</button></div>`;
 let activeRoll=units[0]||0;
 let cream=handroll?(/sin queso crema/i.test(previous?.notes||'')?'no':/con queso crema/i.test(previous?.notes||'')?'si':''):'';
 const notes=()=>{const typed=dialog.querySelector('#unitNotes').value.replace(/(?:con|sin) queso crema\s*[;,.]?/ig,'').trim();return handroll?`${cream==='no'?'Sin':'Con'} queso crema${typed?'; '+typed:''}`:typed;};
 const showRoll=()=>{if(!tabbed)return;dialog.querySelectorAll('[data-roll]').forEach(el=>el.hidden=Number(el.dataset.roll)!==activeRoll);dialog.querySelectorAll('[data-roll-tab]').forEach(el=>el.classList.toggle('selected',Number(el.dataset.rollTab)===activeRoll));dialog.querySelector('.roll-current').textContent=`Handroll ${activeRoll} de ${units.length}`;dialog.querySelector('[data-prev-roll]').disabled=activeRoll===units[0];dialog.querySelector('[data-next-roll]').hidden=activeRoll===units.at(-1);dialog.querySelector('[data-save]').hidden=activeRoll!==units.at(-1);};
 const goRoll=n=>{activeRoll=n;showRoll();};
 const update=()=>{for(const g of gs){const ids=selected[g.id];dialog.querySelectorAll('[data-group-option]').forEach(b=>{if(b.dataset.groupOption!==String(g.id))return;const active=ids.map(String).includes(b.dataset.option);b.classList.toggle('chosen',active);b.setAttribute('aria-pressed',String(active));});const count=dialog.querySelector(`[data-count="${CSS.escape(String(g.id))}"]`);if(count)count.textContent=`${ids.length} seleccionados · máximo ${g.max_select}`;}if(handroll)dialog.querySelectorAll('[data-cream]').forEach(b=>{b.classList.toggle('chosen',b.dataset.cream===cream);b.setAttribute('aria-pressed',String(b.dataset.cream===cream));});if(promo)dialog.querySelector('#changeCounter').textContent=`Cambios: ${changeCount(gs,selected)} de 3`;try{dialog.querySelector('#unitPrice').textContent='Precio: '+clp(pricedUnit(p,gs,selected,notes()).price);}catch(e){dialog.querySelector('#unitPrice').textContent=e.message;}};
 dialog.querySelector('[data-close]').onclick=()=>dialog.close();
 dialog.querySelectorAll('[data-cream]').forEach(b=>b.onclick=()=>{cream=b.dataset.cream;update();});
 dialog.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>{selected[b.dataset.clear]=[];update();});
 dialog.querySelectorAll('[data-group-option]').forEach(b=>b.onclick=()=>{const g=gs.find(x=>String(x.id)===b.dataset.groupOption);if(!g)return;const ids=selected[g.id],id=g.choices.find(x=>String(x.id)===b.dataset.option)?.id;if(id===undefined)return;const index=ids.indexOf(id);if(index>=0)ids.splice(index,1);else if(g.max_select===1){if(promo&&isChange(g)&&changeCount(gs,selected)>=3&&ids.length===0){dialog.querySelector('.quick-error').textContent='Máximo 3 cambios por tabla o promoción.';return;}selected[g.id]=[id];}else if(ids.length<g.max_select){if(promo&&isChange(g)&&changeCount(gs,selected)>=3){dialog.querySelector('.quick-error').textContent='Máximo 3 cambios por tabla o promoción.';return;}ids.push(id);}dialog.querySelector('.quick-error').textContent='';update();});
 dialog.querySelector('#unitNotes').addEventListener('input',update);
 if(tabbed){dialog.querySelectorAll('[data-roll-tab]').forEach(b=>b.onclick=()=>goRoll(Number(b.dataset.rollTab)));dialog.querySelector('[data-prev-roll]').onclick=()=>goRoll(units[Math.max(0,units.indexOf(activeRoll)-1)]);dialog.querySelector('[data-next-roll]').onclick=()=>{const invalid=gs.find(g=>unitOf(g)===activeRoll&&!validateSelection(g,selected[g.id]));if(invalid){dialog.querySelector('.quick-error').textContent=`Completa ${invalid.name}.`;return;}goRoll(units[Math.min(units.length-1,units.indexOf(activeRoll)+1)]);};}
 dialog.querySelector('[data-save]').onclick=()=>{if(handroll&&!cream){dialog.querySelector('.quick-error').textContent='Indica si lleva queso crema.';return;}const invalid=gs.find(g=>!validateSelection(g,selected[g.id]));if(invalid){dialog.querySelector('.quick-error').textContent=`Revisa ${invalid.name}: selecciona entre ${invalid.min_select} y ${invalid.max_select}.`;if(tabbed&&unitOf(invalid))goRoll(unitOf(invalid));return;}try{const item=pricedUnit(p,gs,selected,notes());if(previous)item.quantity=previous.quantity;onSave(item);dialog.close();}catch(e){dialog.querySelector('.quick-error').textContent=e.message;}};
 showRoll();dialog.showModal();update();
}
