import {createClient} from '@supabase/supabase-js';
import rameLogo from './assets/rame-logo.png';
import './style.css';
const target=document.querySelector('#tracking'),token=window.location.hash.slice(1),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const client=import.meta.env.VITE_SUPABASE_URL&&import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}):null;
let timer=null,loaded=false;
function unavailable(){target.innerHTML=`<img class="tracking-logo" src="${rameLogo}" alt="Ramé Sushi"><h1>Seguimiento no disponible</h1><p>El enlace puede haber vencido. Pide al local un nuevo enlace de tu pedido.</p>`;}
async function refresh(){clearTimeout(timer);if(!client||!/^[a-f0-9]{64}$/.test(token)){unavailable();return;}try{const {data:o,error}=await client.rpc('public_order_tracking',{p_token:token});if(error)throw error;if(!o){unavailable();return;}const statuses={pending:'Pedido recibido',confirmed:'En cocina',preparing:'En cocina',ready:o.fulfillment==='delivery'?'Empacando':'Listo para retirar',assigned:'Empacando',out_for_delivery:'En camino',delivered:'Entregado',closed:'Pedido completado',cancelled:'Pedido cancelado'},stage=['pending','confirmed','preparing'].includes(o.status)?0:['ready','assigned'].includes(o.status)?1:2,steps=o.fulfillment==='delivery'?['En cocina','Empacando','En camino']:['En cocina','Listo para retirar','Retirado'];target.innerHTML=`<img class="tracking-logo" src="${rameLogo}" alt="Ramé Sushi"><p>${esc(o.business_name)}</p><h1>Pedido #${String(o.number).padStart(3,'0')}</h1><h2>${esc(statuses[o.status]||'Pedido recibido')}</h2>${o.status==='cancelled'?'':`<ol class="tracking-steps">${steps.map((s,i)=>`<li class="${i<=stage?'reached':''}">${s}</li>`).join('')}</ol>`}${o.scheduled_at?`<p>Agendado para ${new Date(o.scheduled_at).toLocaleString('es-CL',{timeZone:'America/Santiago'})}</p>`:''}<p>El estado se actualiza automáticamente cada 20 segundos.</p><p>Última consulta: ${new Date().toLocaleTimeString('es-CL',{timeZone:'America/Santiago'})}</p><p id="trackingNotice" role="status"></p><button id="refreshTracking">Actualizar ahora</button>`;target.querySelector('#refreshTracking').onclick=refresh;loaded=true;}catch{if(!loaded){target.innerHTML='<h1>No pudimos consultar tu pedido</h1><p>Revisa tu conexión.</p><button id="retryTracking">Reintentar</button>';target.querySelector('button').onclick=refresh;}else target.querySelector('#trackingNotice').textContent='Sin conexión. El estado mostrado corresponde a la última consulta.';}finally{if(!document.hidden)timer=setTimeout(refresh,20000);}}
document.addEventListener('visibilitychange',()=>{clearTimeout(timer);if(!document.hidden)refresh();});refresh();
